/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package blackjack;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author PC
 */
public class Plateau extends javax.swing.JFrame {
    
        //Attributs
    private final byte BLACKJACK = 21;
    private boolean victoire;
    private Joueur j;
    private Donneur d;
    private PaquetDeCartes jeuDeCartes;
    private Graphics monDC ; 

    private byte valeurMainDonneur;
    private byte valeurMainJoueur;
    private int miseJoueur;
    private int indice = 0;
    private int y,x = 50;
    

    /**
     * Creates new form Plateau
     */
    public Plateau() {
        
        j = new Joueur();
        d = new Donneur();
        jeuDeCartes = new PaquetDeCartes();
        
        miseJoueur=j.getMise();
        valeurMainDonneur= d.main.getValeurMain();
        valeurMainJoueur= j.main.getValeurMain();

        initComponents();
        monDC=getGraphics();
  
    }

    /**
     * Méthode détérmination du gagnant
     */
    public void victoire() {

        // victoire du donneur
        // Si la valeur de la main du croupier = 21
        if (valeurMainDonneur == BLACKJACK) {

            victoire = false;
        }
        // victoire du donneur
        // Si la valeur de la main du croupier > celle du joueur
        if(valeurMainJoueur< valeurMainDonneur){
        
            victoire = false;
        }
         // victoire du donneur
        // Si la valeur de la main du croupier = celle du joueur
        if(valeurMainJoueur == valeurMainDonneur){
            victoire = false;
        }
        // victoire du joueur
        // Si la valeur de la main du joueur > celle du croupier
        if(valeurMainJoueur > valeurMainDonneur){
        
            victoire = true;
        }
    
 
    }
    
    public PaquetDeCartes getPaquet(){
        return jeuDeCartes;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bouton5 = new javax.swing.JButton();
        boutonTirer = new javax.swing.JButton();
        Rester = new javax.swing.JButton();
        Doubler = new javax.swing.JButton();
        valeurMise = new javax.swing.JLabel();
        argent = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bouton10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setName("Blackjack"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 1024));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bouton5.setText("5");
        bouton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bouton5MouseClicked(evt);
            }
        });
        bouton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton5ActionPerformed(evt);
            }
        });
        getContentPane().add(bouton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        boutonTirer.setText("Tirer");
        boutonTirer.setRolloverEnabled(false);
        boutonTirer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonTirerMouseClicked(evt);
            }
        });
        getContentPane().add(boutonTirer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, -1, -1));

        Rester.setText("Rester");
        getContentPane().add(Rester, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, -1, -1));

        Doubler.setText("Doubler");
        getContentPane().add(Doubler, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, -1, -1));
        getContentPane().add(valeurMise, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 50, 20));
        getContentPane().add(argent, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 50, 20));

        jLabel1.setText("Argent total : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        bouton10.setText("10");
        bouton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bouton10MouseClicked(evt);
            }
        });
        getContentPane().add(bouton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        jLabel2.setText("Valeur de la mise :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 140, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TapisDeCartesBJ.png"))); // NOI18N
        jLabel3.setAutoscrolls(true);
        jLabel3.setFocusable(false);
        jLabel3.setName(""); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 1024));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void bouton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bouton10MouseClicked
       
        miseJoueur = miseJoueur + 10;
        valeurMise.setText(String.valueOf(miseJoueur));
       
    }//GEN-LAST:event_bouton10MouseClicked

    private void bouton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bouton5MouseClicked
       
        miseJoueur = miseJoueur + 5;
        valeurMise.setText(String.valueOf(miseJoueur));
    }//GEN-LAST:event_bouton5MouseClicked

    private void bouton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bouton5ActionPerformed

    private void boutonTirerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonTirerMouseClicked
        // TODO add your handling code here:
        
        j.tirer(jeuDeCartes);
   
        //  monDC.drawString("titi est content", 200, 200);
        Image img = Toolkit.getDefaultToolkit().getImage("src/image/" + jeuDeCartes.recuperIdCarte(indice) + ".png");  
               
        monDC.drawImage(img, 200 + x*indice, 200 + y*indice, null);
        Image img2 = Toolkit.getDefaultToolkit().getImage("src/image/" + jeuDeCartes.recuperIdCarte(indice+1) + ".png");  
        monDC.drawImage(img2, 200 + x*(indice+1), 200 + y*(indice+1), null);
        valeurMise.setText(String.valueOf(jeuDeCartes.recuperIdCarte(indice)));
        argent.setText(String.valueOf((indice)));
        indice++;
        
    }//GEN-LAST:event_boutonTirerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Plateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Plateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Plateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Plateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Plateau().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Doubler;
    private javax.swing.JButton Rester;
    private javax.swing.JLabel argent;
    private javax.swing.JButton bouton10;
    private javax.swing.JButton bouton5;
    private javax.swing.JButton boutonTirer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel valeurMise;
    // End of variables declaration//GEN-END:variables
}
